# Generated by Django 5.1.5 on 2025-01-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_marketitem_delete_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketItem',
        ),
    ]
