# Generated by Django 5.1.5 on 2025-01-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_delete_marketitem'),
        ('products', '0012_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
