# Generated by Django 5.1.5 on 2025-01-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_market_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='products',
        ),
    ]
