# Generated by Django 5.1.5 on 2025-01-26 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_marketitem'),
        ('products', '0012_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='markets.market'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
