# Generated by Django 5.1.5 on 2025-01-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_marketitem_available_alter_marketitem_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
