# Generated by Django 5.1.5 on 2025-01-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_alter_marketitem_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitem',
            name='price',
        ),
    ]
