# Generated by Django 5.1.5 on 2025-01-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_remove_marketitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='markets.marketitem')),
            ],
        ),
    ]
