# Generated by Django 5.1.5 on 2025-01-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('products', '0003_alter_product_barcode_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markets',
            field=models.ManyToManyField(blank=True, related_name='products', to='markets.market'),
        ),
    ]
