# Generated by Django 5.1.5 on 2025-01-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('products', '0009_alter_price_created_at_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='markets.market'),
        ),
    ]
