# Generated by Django 5.1.5 on 2025-01-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_price_market'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
